"""initial migration

Revision ID: c9b27415f8de
Revises: dfca0e067627
Create Date: 2021-05-28 23:09:20.151926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b27415f8de'
down_revision = 'dfca0e067627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
