"""initial migration

Revision ID: f4cb1d642c93
Revises: c9b27415f8de
Create Date: 2021-05-28 23:22:20.313121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cb1d642c93'
down_revision = 'c9b27415f8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
